# Mapping constants

MIN_ZOOM_LEVEL = 1
MAX_ZOOM_LEVEL = 21
MAX_VISIBLE_ZOOM = 16
MAP_WIDTH_IN_PX = 400
MAP_HEIGHT_IN_PX = 400
SMALL_ICON_HEIGHT = 23 
SMALL_ICON_WIDTH = 20
LARGE_ICON_HEIGHT = 37
LARGE_ICON_WIDTH = 32
MIN_ZOOM_FOR_OTHER_MARKERS = 15