# Mapping constants

MIN_ZOOM_LEVEL = 8
MAX_ZOOM_LEVEL = 21
MAX_VISIBLE_ZOOM = 16

MAP_WIDTH = 400
MAP_HEIGHT = 400

LARGE_MAP_WIDTH = 500
LARGE_MAP_HEIGHT = 500

CAMPAIGN_PAGE_MAP_HEIGHT = 160
CAMPAIGN_PAGE_MAP_WIDTH = 300

LOCATION_PAGE_MAP_HEIGHT = 490
LOCATION_PAGE_MAP_WIDTH = 590

PROBLEM_CREATION_MAP_HEIGHT = 350
PROBLEM_CREATION_MAP_WIDTH = 450

BROWSE_MAP_HEIGHT = 490
BROWSE_MAP_WIDTH = 490

ALL_HEIGHTS = [MAP_HEIGHT,
               LARGE_MAP_HEIGHT,
               CAMPAIGN_PAGE_MAP_HEIGHT,
               LOCATION_PAGE_MAP_HEIGHT,
               PROBLEM_CREATION_MAP_HEIGHT,
               BROWSE_MAP_HEIGHT]
ALL_WIDTHS = [MAP_WIDTH,
              LARGE_MAP_WIDTH,
              CAMPAIGN_PAGE_MAP_WIDTH,
              LOCATION_PAGE_MAP_WIDTH,
              PROBLEM_CREATION_MAP_WIDTH,
              BROWSE_MAP_WIDTH]

SMALL_ICON_HEIGHT = 31
SMALL_ICON_WIDTH = 26
LARGE_ICON_HEIGHT = 46
LARGE_ICON_WIDTH = 39
MIN_ZOOM_FOR_OTHER_MARKERS = 14
MIN_ZOOM_FOR_HIGHLIGHTED_MARKERS = 8
