#!/bin/bash

LOC=`dirname $0`

if [ $1 == 'verbose' ]
    then 
    $LOC/runner 'ProblemMailer.send_reports(dryrun=false, verbose=true)'
    else
    $LOC/runner 'ProblemMailer.send_reports(dryrun=false)'
fi 



